<a href="https://colab.research.google.com/github/EVRJSASTRY/NASSCOM-AI/blob/main/Day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import random
from datetime import datetime, timedelta

# Constants
DEVICE_TYPES = ["Temperature", "Humidity", "Pressure", "Light"]
LOCATIONS = ["Room_A", "Room_B", "Lab_1", "Lab_2", "Warehouse"]

READING_RANGES = {
    "Temperature": (15.0, 40.0),  # °C
    "Humidity": (20.0, 90.0),     # %
    "Pressure": (950.0, 1050.0),  # hPa
    "Light": (100.0, 1000.0)      # Lux
}

# Generate simulated sensor readings
raw_sensor_data = []

start_time = datetime.now()

for i in range(1, 101):
    device_id = f"DEV{i:03d}"
    device_type = random.choice(DEVICE_TYPES)
    location = random.choice(LOCATIONS)

    min_val, max_val = READING_RANGES[device_type]
    value = round(random.uniform(min_val, max_val), 2)

    timestamp = start_time + timedelta(seconds=i)
    timestamp_str = timestamp.strftime("%Y-%m-%d %H:%M:%S")

    raw_sensor_data.append(
        (timestamp_str, device_id, device_type, location, value)
    )

# Example: Print first 5 readings
for reading in raw_sensor_data[:99]:
    print(reading)

('2026-06-10 09:10:00', 'DEV001', 'Temperature', 'Warehouse', 24.23)
('2026-06-10 09:10:01', 'DEV002', 'Humidity', 'Lab_2', 53.67)
('2026-06-10 09:10:02', 'DEV003', 'Humidity', 'Lab_1', 31.42)
('2026-06-10 09:10:03', 'DEV004', 'Humidity', 'Room_B', 62.61)
('2026-06-10 09:10:04', 'DEV005', 'Light', 'Warehouse', 894.66)
('2026-06-10 09:10:05', 'DEV006', 'Humidity', 'Warehouse', 84.39)
('2026-06-10 09:10:06', 'DEV007', 'Temperature', 'Room_A', 20.85)
('2026-06-10 09:10:07', 'DEV008', 'Humidity', 'Warehouse', 46.2)
('2026-06-10 09:10:08', 'DEV009', 'Temperature', 'Warehouse', 20.49)
('2026-06-10 09:10:09', 'DEV010', 'Temperature', 'Warehouse', 26.21)
('2026-06-10 09:10:10', 'DEV011', 'Humidity', 'Room_B', 36.13)
('2026-06-10 09:10:11', 'DEV012', 'Pressure', 'Lab_2', 1039.65)
('2026-06-10 09:10:12', 'DEV013', 'Temperature', 'Room_A', 15.18)
('2026-06-10 09:10:13', 'DEV014', 'Humidity', 'Room_B', 60.88)
('2026-06-10 09:10:14', 'DEV015', 'Pressure', 'Warehouse', 969.05)
('2026-06-10 09:10:15'

In [3]:
(timestamp_str, device_id, device_type, location, value)

('2026-06-10 09:11:39', 'DEV100', 'Light', 'Lab_1', 567.7)

In [8]:
temperature_readings = []

for reading in raw_sensor_data:
    timestamp, device_id, device_type, location, value = reading

    if device_type == "Temperature_Sensor":
        temp_dict = {
            "timestamp": timestamp,
            "device_id": device_id,
            "location": location,
            "temperature_celsius": value
        }
        temperature_readings.append(temp_dict)

# Print first 5 records
print(temperature_readings[:5])

[]


In [9]:
unique_locations = set()

for reading in raw_sensor_data:
    unique_locations.add(reading[3])

print(unique_locations)

{'Room_B', 'Lab_1', 'Room_A', 'Lab_2', 'Warehouse'}


In [10]:
import numpy as np
u = np.array([2,3])
v = np.array ([4,1])
print("u+v=",u+v)

u+v= [6 4]


In [11]:
# Student score vectors: [Math, Science, English]

student1 = [85, 90, 78]
student2 = [92, 88, 95]
student3 = [76, 81, 84]

# Store all vectors in a list
student_scores = [student1, student2, student3]

print(student_scores)

[[85, 90, 78], [92, 88, 95], [76, 81, 84]]


In [12]:
import numpy as np

s1 = np.array([85, 90, 78])
s2 = np.array([92, 88, 95])
s3 = np.array([76, 81, 84])

# L2 norms
print("L2 Norms:")
for i, s in enumerate([s1, s2, s3], start=1):
    print(f"Student {i}: {np.linalg.norm(s):.2f}")

# Cosine similarity
def cosine_similarity(a, b):
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

print("\nCosine Similarities:")
print("S1-S2:", cosine_similarity(s1, s2))
print("S1-S3:", cosine_similarity(s1, s3))
print("S2-S3:", cosine_similarity(s2, s3))

L2 Norms:
Student 1: 146.32
Student 2: 158.85
Student 3: 139.26

Cosine Similarities:
S1-S2: 0.9960206910425076
S1-S3: 0.9963642434993939
S2-S3: 0.9990456452788646


In [13]:
import numpy as np

A = np.array([
    [2, 3, 1],
    [1, 2, 4],
    [3, 1, 2]
])

B = np.array([110, 90, 130])

X = np.linalg.solve(A, B)

print("Notebook Price =", round(X[0], 2))
print("Pen Price      =", round(X[1], 2))
print("Pencil Price   =", round(X[2], 2))

Notebook Price = 34.0
Pen Price      = 11.2
Pencil Price   = 8.4


In [14]:
import numpy as np

# Coefficient matrix
A = np.array([
    [2, 3, 1],
    [1, 2, 4],
    [3, 1, 2]
])

# Constants vector
B = np.array([110, 90, 130])

# Solve the system
X = np.linalg.solve(A, B)

print("Solution [x, y, z]:")
print(X)

# Verification
print("\nVerification (A @ X):")
print(A @ X)

print("\nOriginal B:")
print(B)

print("\nVerification passed:",
      np.allclose(A @ X, B))

Solution [x, y, z]:
[34.  11.2  8.4]

Verification (A @ X):
[110.  90. 130.]

Original B:
[110  90 130]

Verification passed: True
